# Generated by ChatGPT

#!/usr/bin/env python3
"""
Science production-flow and operational-loop analysis for PropertyRandomizer.

This is deliberately separate from per-material cost solving.

For one Pyanodons science boundary:
  1. Solve one coherent primal production plan for the exported science bundle.
  2. Restrict to recipe rows actually active in that plan.
  3. Build a GROSS product -> ingredient graph from those recipes.
  4. Protect a recipe/ingredient edge iff one of that recipe's gross products
     lies with the ingredient on a simple cycle of length <= max_cycle_length.

No SCC/transitive closure is taken.
"""

from __future__ import annotations

import json
from collections import defaultdict, deque
from pathlib import Path
from typing import Any

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix, vstack


def science_current(lp: dict[str, Any]) -> dict[str, Any] | None:
    current = (lp.get("science") or {}).get("current")
    return current if current else None


def has_science_target(lp: dict[str, Any]) -> bool:
    current = science_current(lp)
    return bool(current and current.get("requirements"))


def science_requirements(lp: dict[str, Any]) -> list[dict[str, Any]]:
    current = science_current(lp)
    if current is None:
        return []

    requirements = current.get("requirements") or []

    for req in requirements:
        if req.get("material_index") is None:
            raise RuntimeError(
                f"Science requirement lacks material_index: {req!r}"
            )

    return requirements



def flow_extra_rows(lp: dict[str, Any]) -> list[dict[str, Any]]:
    return list((lp.get("science") or {}).get("flow_extra_rows") or [])


def all_flow_rows(lp: dict[str, Any]) -> list[dict[str, Any]]:
    return [*(lp.get("rows") or []), *flow_extra_rows(lp)]


def build_flow_matrix(A, b: np.ndarray, lp: dict[str, Any]):
    """
    Append science.flow_extra_rows to the exported COST matrix.

    These rows exist only for the production-flow solve.  They are intentionally
    absent from lp["rows"], so per-material staged costs remain "pre-pack".
    """
    extras = flow_extra_rows(lp)

    if not extras:
        return A, np.asarray(b, dtype=float)

    n_materials = A.shape[1]

    rr: list[int] = []
    cc: list[int] = []
    vv: list[float] = []
    extra_b = np.zeros(len(extras), dtype=float)

    for local_row, row in enumerate(extras):
        extra_b[local_row] = float(row["cost"])

        for lua_col, coefficient in row.get("coeffs") or []:
            rr.append(local_row)
            cc.append(int(lua_col) - 1)
            vv.append(float(coefficient))

    extra_A = coo_matrix(
        (vv, (rr, cc)),
        shape=(len(extras), n_materials),
    ).tocsr()

    return (
        vstack([A, extra_A], format="csr"),
        np.concatenate([np.asarray(b, dtype=float), extra_b]),
    )


def _solve_target(A, b: np.ndarray, target: np.ndarray, method: str):
    return linprog(
        c=b,
        A_ub=-A.T,
        b_ub=-target,
        bounds=(0, None),
        method=method,
        options={"presolve": True},
    )


def diagnose_infeasible_requirements(
    A,
    b: np.ndarray,
    requirements: list[dict[str, Any]],
    method: str,
) -> list[dict[str, Any]]:
    """
    Cheap diagnostic: test each requested science pack independently using the
    SAME augmented flow matrix.

    If a requirement is individually infeasible, the combined science bundle
    cannot be feasible either.  This catches remaining source-model gaps such
    as a science pack whose own ingredient chain contains an unproducible
    material.
    """
    bad: list[dict[str, Any]] = []

    for requirement in requirements:
        target = np.zeros(A.shape[1], dtype=float)
        target[int(requirement["material_index"]) - 1] = float(
            requirement["amount"]
        )

        result = _solve_target(A, b, target, method)

        if result.status != 0:
            bad.append(
                {
                    "name": requirement["name"],
                    "key": requirement.get("key"),
                    "amount": float(requirement["amount"]),
                    "solver_status": int(result.status),
                    "message": result.message,
                }
            )

    return bad

def solve_science_flow(
    A,
    b: np.ndarray,
    lp: dict[str, Any],
    method: str = "highs",
    active_eps: float = 1e-9,
) -> dict[str, Any]:
    """
    Solve the production primal

        min b^T y
        s.t. A^T y >= science_target
             y >= 0

    for the exact science quantities exported for this Py boundary.
    """
    requirements = science_requirements(lp)

    if not requirements:
        return {
            "status": "skipped_no_science_target",
            "objective": None,
            "science": science_current(lp),
            "requirements": [],
            "active_rows": [],
        }

    target = np.zeros(A.shape[1], dtype=float)

    for req in requirements:
        target[int(req["material_index"]) - 1] += float(req["amount"])

    flow_A, flow_b = build_flow_matrix(A, b, lp)

    result = _solve_target(
        flow_A,
        flow_b,
        target,
        method,
    )

    if result.status != 0:
        status = (
            "infeasible" if result.status == 2
            else "unbounded" if result.status == 3
            else f"solver_status_{result.status}"
        )
        return {
            "status": status,
            "objective": None,
            "science": science_current(lp),
            "requirements": requirements,
            "flow_extra_row_count": len(flow_extra_rows(lp)),
            "infeasible_requirements": diagnose_infeasible_requirements(
                flow_A,
                flow_b,
                requirements,
                method,
            ),
            "active_rows": [],
            "message": result.message,
            "nit": getattr(result, "nit", None),
        }

    usages = np.asarray(result.x, dtype=float)
    flow_rows = all_flow_rows(lp)

    if len(flow_rows) != len(usages):
        raise RuntimeError(
            "Flow row metadata/activity length mismatch: "
            f"{len(flow_rows)} rows vs {len(usages)} usages"
        )

    active_rows: list[dict[str, Any]] = []

    for position, row in enumerate(flow_rows):
        usage = float(usages[position])
        if usage <= active_eps:
            continue

        row_index = int(row["index"])

        active_rows.append(
            {
                "index": row_index,
                "usage": usage,
                "row_cost": float(row["cost"]),
                "cost_contribution": usage * float(row["cost"]),
                "source_type": row.get("source_type"),
                "source_name": row.get("source_name"),
                "gross_ingredients": row.get("gross_ingredients") or [],
                "gross_products": row.get("gross_products") or [],
            }
        )

    return {
        "status": "optimal",
        "objective": float(result.fun),
        "science": science_current(lp),
        "requirements": requirements,
        "flow_extra_row_count": len(flow_extra_rows(lp)),
        "active_rows": active_rows,
        "message": result.message,
        "nit": getattr(result, "nit", None),
    }


def _positive_entries(
    row: dict[str, Any],
    field: str,
) -> list[dict[str, Any]]:
    return [
        entry
        for entry in (row.get(field) or [])
        if entry.get("key")
        and float(entry.get("amount", 0.0)) > 0.0
    ]


def _shortest_path_bounded(
    adjacency: dict[str, dict[str, list[dict[str, Any]]]],
    start: str,
    goal: str,
    max_edges: int,
):
    """
    Return one shortest path start -> goal with at most max_edges.

    BFS visits each node once, so the returned witness path is simple.
    """
    if start == goal:
        return [start], []

    queue = deque([(start, 0)])
    parent_node: dict[str, str | None] = {start: None}
    parent_edge: dict[str, dict[str, Any]] = {}

    while queue:
        node, depth = queue.popleft()

        if depth >= max_edges:
            continue

        for nxt, witnesses in adjacency.get(node, {}).items():
            if nxt in parent_node:
                continue

            parent_node[nxt] = node
            parent_edge[nxt] = witnesses[0]

            if nxt == goal:
                nodes = [goal]
                edges: list[dict[str, Any]] = []
                current = goal

                while current != start:
                    edges.append(parent_edge[current])
                    current = parent_node[current]
                    nodes.append(current)

                nodes.reverse()
                edges.reverse()
                return nodes, edges

            queue.append((nxt, depth + 1))

    return None


def analyze_operational_loops(
    lp: dict[str, Any],
    flow: dict[str, Any],
    max_cycle_length: int = 10,
) -> dict[str, Any]:
    """
    Find recipe/ingredient edges participating in short simple cycles among
    recipes simultaneously active in the solved science production flow.
    """
    if flow.get("status") != "optimal":
        return {
            "status": "flow_not_optimal",
            "max_cycle_length": max_cycle_length,
            "protected_edges": [],
            "stats": {},
        }

    rows_by_index = {
        int(row["index"]): row
        for row in all_flow_rows(lp)
    }

    active_usage = {
        int(row["index"]): float(row["usage"])
        for row in flow.get("active_rows", [])
        if float(row.get("usage", 0.0)) > 0.0
    }

    # adjacency[product][ingredient] = gross dependency witnesses.
    adjacency: dict[
        str,
        dict[str, list[dict[str, Any]]],
    ] = defaultdict(lambda: defaultdict(list))

    active_recipe_rows = []

    for row_index, usage in active_usage.items():
        row = rows_by_index[row_index]

        if row.get("source_type") != "recipe":
            continue

        ingredients = _positive_entries(row, "gross_ingredients")
        products = _positive_entries(row, "gross_products")

        if not ingredients or not products:
            continue

        active_recipe_rows.append(
            (row, usage, ingredients, products)
        )

        for product in products:
            for ingredient in ingredients:
                adjacency[product["key"]][ingredient["key"]].append(
                    {
                        "from": product["key"],
                        "to": ingredient["key"],
                        "row_index": row_index,
                        "recipe": row.get("source_name"),
                    }
                )

    protected: list[dict[str, Any]] = []
    seen: set[tuple[int, str]] = set()

    for row, usage, ingredients, products in active_recipe_rows:
        row_index = int(row["index"])
        recipe_name = row.get("source_name")

        for ingredient in ingredients:
            ingredient_key = ingredient["key"]
            best = None

            for product in products:
                product_key = product["key"]

                # Original gross dependency is:
                #     product -> ingredient
                #
                # Find a return path:
                #     ingredient -> ... -> product
                #
                # The two together form a simple cycle.
                path = _shortest_path_bounded(
                    adjacency,
                    start=ingredient_key,
                    goal=product_key,
                    max_edges=max_cycle_length - 1,
                )

                if path is None:
                    continue

                return_nodes, return_edges = path
                cycle_length = 1 + len(return_edges)

                if cycle_length > max_cycle_length:
                    continue

                candidate = {
                    "min_cycle_length": cycle_length,
                    "via_product": product_key,
                    "return_nodes": return_nodes,
                    "return_edges": return_edges,
                }

                if (
                    best is None
                    or cycle_length < best["min_cycle_length"]
                ):
                    best = candidate

            if best is None:
                continue

            dedupe = (row_index, ingredient_key)
            if dedupe in seen:
                continue
            seen.add(dedupe)

            protected.append(
                {
                    "row_index": row_index,
                    "recipe": recipe_name,
                    "ingredient": ingredient_key,
                    "ingredient_amount_per_use": float(
                        ingredient["amount"]
                    ),
                    "row_usage": usage,
                    "min_cycle_length": int(
                        best["min_cycle_length"]
                    ),
                    "via_product": best["via_product"],
                    # First/last node intentionally repeat to show closure.
                    "cycle_nodes": [
                        best["via_product"],
                        *best["return_nodes"],
                    ],
                    "cycle_return_edges": best["return_edges"],
                }
            )

    protected.sort(
        key=lambda edge: (
            int(edge["min_cycle_length"]),
            int(edge["row_index"]),
            str(edge["ingredient"]),
        )
    )

    by_length: dict[int, int] = defaultdict(int)
    for edge in protected:
        by_length[int(edge["min_cycle_length"])] += 1

    return {
        "status": "optimal",
        "max_cycle_length": max_cycle_length,
        "protected_edges": protected,
        "stats": {
            "active_recipe_rows": len(active_recipe_rows),
            "protected_recipe_ingredient_edges": len(protected),
            "protected_by_min_cycle_length": {
                str(length): by_length[length]
                for length in sorted(by_length)
            },
        },
    }


def _lua_quote(value: str) -> str:
    return json.dumps(value)


def write_loops_lua(
    path: Path,
    loops: dict[str, Any],
) -> None:
    """
    Lua map convenient for the randomizer:

        protected_edges[recipe_name][ingredient_key]
    """
    lines = [
        "-- generated by science_flow.py / solve_lp_levels.py",
        "return {",
        f"    max_cycle_length = "
        f"{int(loops.get('max_cycle_length', 0))},",
        "    protected_edges = {",
    ]

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)

    for edge in loops.get("protected_edges", []):
        grouped[str(edge["recipe"])].append(edge)

    for recipe in sorted(grouped):
        lines.append(f"        [{_lua_quote(recipe)}] = {{")

        for edge in sorted(
            grouped[recipe],
            key=lambda item: item["ingredient"],
        ):
            lines.append(
                f"            [{_lua_quote(edge['ingredient'])}] = {{"
            )
            lines.append(
                f"                min_cycle_length = "
                f"{int(edge['min_cycle_length'])},"
            )
            lines.append(
                f"                via_product = "
                f"{_lua_quote(edge['via_product'])},"
            )
            lines.append("                cycle_nodes = {")

            for node in edge["cycle_nodes"]:
                lines.append(
                    f"                    {_lua_quote(node)},"
                )

            lines.append("                },")
            lines.append("            },")

        lines.append("        },")

    lines.extend(["    },", "}"])

    path.write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )
