-- generated by chatGPT

local simplex_cost = require("lib/cost/simplex-cost")
local gutils = require("new-lib/graph/graph-utils")

local simplex_lp_export = {}

local CHUNK_SIZE = 8000

local function json_escape_string(s)
    s = tostring(s)

    s = string.gsub(s, "\\", "\\\\")
    s = string.gsub(s, "\"", "\\\"")
    s = string.gsub(s, "\b", "\\b")
    s = string.gsub(s, "\f", "\\f")
    s = string.gsub(s, "\n", "\\n")
    s = string.gsub(s, "\r", "\\r")
    s = string.gsub(s, "\t", "\\t")

    return "\"" .. s .. "\""
end

local function is_array(t)
    local max_index = 0
    local count = 0

    for k, _ in pairs(t) do
        if type(k) ~= "number" or k < 1 or k % 1 ~= 0 then
            return false
        end

        if k > max_index then
            max_index = k
        end

        count = count + 1
    end

    return count == max_index
end

local function sorted_keys(t)
    local keys = {}

    for k, _ in pairs(t) do
        keys[#keys + 1] = k
    end

    table.sort(keys, function(a, b)
        return tostring(a) < tostring(b)
    end)

    return keys
end

local function json_encode(value)
    local value_type = type(value)

    if value_type == "nil" then
        return "null"
    elseif value_type == "boolean" then
        return value and "true" or "false"
    elseif value_type == "number" then
        if value ~= value then
            error("Cannot encode NaN as JSON")
        end

        if value == math.huge or value == -math.huge then
            error("Cannot encode infinity as JSON")
        end

        return string.format("%.17g", value)
    elseif value_type == "string" then
        return json_escape_string(value)
    elseif value_type == "table" then
        if is_array(value) then
            local parts = {}

            for i = 1, #value do
                parts[#parts + 1] = json_encode(value[i])
            end

            return "[" .. table.concat(parts, ",") .. "]"
        else
            local parts = {}

            for _, key in pairs(sorted_keys(value)) do
                local encoded_key = json_escape_string(key)
                local encoded_value = json_encode(value[key])
                parts[#parts + 1] = encoded_key .. ":" .. encoded_value
            end

            return "{" .. table.concat(parts, ",") .. "}"
        end
    else
        error("Cannot encode value of type " .. value_type .. " as JSON")
    end
end

local function sparse_row_to_coeff_pairs(row)
    local coeffs = {}

    for col, value in pairs(row) do
        if value ~= 0 then
            coeffs[#coeffs + 1] = {col, value}
        end
    end

    table.sort(coeffs, function(a, b)
        return a[1] < b[1]
    end)

    return coeffs
end

local function emit_chunked_json(json_string)
    log("PROPERTYRANDOMIZER_LP_JSON_BEGIN")

    local len = string.len(json_string)
    local pos = 1

    while pos <= len do
        local chunk = string.sub(json_string, pos, pos + CHUNK_SIZE - 1)
        log("PROPERTYRANDOMIZER_LP_JSON_CHUNK " .. chunk)
        pos = pos + CHUNK_SIZE
    end

    log("PROPERTYRANDOMIZER_LP_JSON_END")
end

function simplex_lp_export.build_export_object()
    local matrix_info = simplex_cost.make_recipe_material_matrix()

    local materials = {}
    for i, material in pairs(matrix_info.material_list) do
        materials[#materials + 1] = {
            index = i,
            key = gutils.key(material),
            type = material.type,
            name = material.name,
        }
    end

    table.sort(materials, function(a, b)
        return a.index < b.index
    end)

    local rows = {}
    for i, row in pairs(matrix_info.matrix) do
        rows[#rows + 1] = {
            index = i,
            cost = matrix_info.cost_column[i],
            coeffs = sparse_row_to_coeff_pairs(row),
        }
    end

    table.sort(rows, function(a, b)
        return a.index < b.index
    end)

    return {
        format = "propertyrandomizer-lp-v1",
        lua_indexed = true,

        description = {
            variables = "material prices p[j]",
            objective = "for each target material t, maximize p[t]",
            constraints = "A p <= b, p >= 0",
            row_coefficients = "positive means produced/output, negative means consumed/input",
        },

        num_materials = #matrix_info.material_list,
        num_rows = #matrix_info.matrix,

        materials = materials,
        rows = rows,
    }
end

function simplex_lp_export.export_to_log()
    log("Constructing simplex LP export object")

    local export_object = simplex_lp_export.build_export_object()
    local json_string = json_encode(export_object)

    log(
        "Exporting simplex LP JSON"
        .. " materials=" .. tostring(export_object.num_materials)
        .. " rows=" .. tostring(export_object.num_rows)
        .. " chars=" .. tostring(string.len(json_string))
    )

    emit_chunked_json(json_string)

    log("Finished simplex LP JSON export")
end

return simplex_lp_export