-- Generated by ChatGPT
-- This file is only used for cost table creation and not run on game startup

-- PropertyRandomizer simplex LP exporter.
--
-- Supports two modes:
--
--   Pyanodons staged mode:
--     export_to_log(sort_info, stage_index)
--     or export_to_log(sort_info, {is_pyanodons=true, stage_index=...})
--
--     Stages 1..10 use matrix_info.pack_level_to_packs for the science
--     production/loop target at that boundary. The matrix itself represents
--     the game immediately BEFORE that science pack can be used for research.
--
--     Stage 11 is the unrestricted/final Py matrix. It still gets a staged
--     material-cost table, but carries NO science target, so flow/loop work is
--     skipped for that stage.
--
--   Generic / Space Age mode:
--     export_to_log(sort_info)
--     or export_to_log(sort_info, {is_pyanodons=false, ...})
--
--     pack_level_to_packs is NEVER read.  By default no science-production
--     target is attached, so Python skips production-plan/loop solving and
--     computes one material-cost table.  To request a production plan/loops,
--     pass either:
--
--       {is_pyanodons=false, technology="some-technology"}
--
--     or:
--
--       {
--         is_pyanodons=false,
--         name="my-science-bundle",
--         requirements={
--           {"automation-science-pack", 1},
--           {"space-science-pack", 1},
--         },
--       }
--
-- The optimization matrix remains NET stoichiometry.  Gross recipe
-- ingredients/results are exported separately so returned cages, catalysts,
-- barrels, temperature carriers, etc. remain visible to loop detection.

local simplex_cost = require("lib/cost/simplex-cost")
local cutils = require("lib/cost/cost-utils")
local constants = require("helper-tables/constants")
local gutils = require("lib/graph/graph-utils")

local simplex_lp_export = {}

local CHUNK_SIZE = 8000

local PY_PACKS_IN_ORDER = {
    "automation-science-pack",
    "py-science-pack-1",
    "logistic-science-pack",
    "military-science-pack",
    "py-science-pack-2",
    "chemical-science-pack",
    "py-science-pack-3",
    "production-science-pack",
    "py-science-pack-4",
    "utility-science-pack",
    "space-science-pack",
}

local PY_STAGE_COUNT = #PY_PACKS_IN_ORDER + 1

local function detect_pyanodons()
    return mods["pycoalprocessing"] ~= nil
        or mods["pyalienlife"] ~= nil
        or mods["pyalternativeenergy"] ~= nil
        or mods["pyhightech"] ~= nil
end

local function json_escape_string(s)
    s = tostring(s)
    s = string.gsub(s, "\\", "\\\\")
    s = string.gsub(s, "\"", "\\\"")
    s = string.gsub(s, "\b", "\\b")
    s = string.gsub(s, "\f", "\\f")
    s = string.gsub(s, "\n", "\\n")
    s = string.gsub(s, "\r", "\\r")
    s = string.gsub(s, "\t", "\\t")
    return "\"" .. s .. "\""
end

local function is_array(t)
    local max_index = 0
    local count = 0

    for k, _ in pairs(t) do
        if type(k) ~= "number" or k < 1 or k % 1 ~= 0 then
            return false
        end
        if k > max_index then
            max_index = k
        end
        count = count + 1
    end

    return count == max_index
end

local function sorted_keys(t)
    local keys = {}
    for k, _ in pairs(t) do
        keys[#keys + 1] = k
    end
    table.sort(keys, function(a, b)
        return tostring(a) < tostring(b)
    end)
    return keys
end

local function json_encode(value)
    local value_type = type(value)

    if value_type == "nil" then
        return "null"
    elseif value_type == "boolean" then
        return value and "true" or "false"
    elseif value_type == "number" then
        if value ~= value then
            error("Cannot encode NaN as JSON")
        end
        if value == math.huge or value == -math.huge then
            error("Cannot encode infinity as JSON")
        end
        return string.format("%.17g", value)
    elseif value_type == "string" then
        return json_escape_string(value)
    elseif value_type == "table" then
        local parts = {}

        if is_array(value) then
            for i = 1, #value do
                parts[#parts + 1] = json_encode(value[i])
            end
            return "[" .. table.concat(parts, ",") .. "]"
        end

        for _, key in pairs(sorted_keys(value)) do
            parts[#parts + 1] =
                json_escape_string(key) .. ":" .. json_encode(value[key])
        end
        return "{" .. table.concat(parts, ",") .. "}"
    end

    error("Cannot encode value of type " .. value_type .. " as JSON")
end

local function sparse_row_to_coeff_pairs(row)
    local coeffs = {}

    for col, value in pairs(row or {}) do
        if value ~= 0 then
            coeffs[#coeffs + 1] = {col, value}
        end
    end

    table.sort(coeffs, function(a, b)
        return a[1] < b[1]
    end)

    return coeffs
end

local function sparse_gross_row_to_entries(row, material_list)
    local entries = {}

    for material_index, amount in pairs(row or {}) do
        if amount ~= 0 then
            local material = material_list[material_index]
            if material == nil then
                error(
                    "Gross recipe row references missing material index "
                    .. tostring(material_index)
                )
            end

            entries[#entries + 1] = {
                key = gutils.key(material),
                amount = amount,
            }
        end
    end

    table.sort(entries, function(a, b)
        return a.key < b.key
    end)

    return entries
end


-- Construct exactly one recipe row for SCIENCE FLOW ONLY.
--
-- The staged material-cost matrix intentionally excludes the current science
-- pack recipe.  To test whether the new pack can be manufactured before any
-- technology using that pack is researched, the flow LP needs that one recipe
-- row added back without adding any later technology-unlocked recipes.
local function add_recipe_entries_to_rows(
    entries,
    sign,
    net_row,
    gross_row,
    matrix_info
)
    for _, entry in pairs(entries or {}) do
        local material_type = entry.type or "item"
        local material_key = gutils.key(material_type, entry.name)
        local material_index = matrix_info.material_to_ind[material_key]

        if material_index == nil then
            error(
                "Science flow recipe entry "
                .. tostring(material_key)
                .. " is missing from material_to_ind"
            )
        end

        local amount = cutils.find_amount_in_entry(entry)

        if amount ~= 0 then
            gross_row[material_index] =
                (gross_row[material_index] or 0) + amount

            local new_net =
                (net_row[material_index] or 0) + sign * amount

            if math.abs(new_net) < 1e-12 then
                net_row[material_index] = nil
            else
                net_row[material_index] = new_net
            end
        end
    end
end

local function matrix_contains_recipe(matrix_info, recipe_name)
    for _, source in pairs(matrix_info.row_sources or {}) do
        if source.type == "recipe" and source.name == recipe_name then
            return true
        end
    end
    return false
end

local function build_flow_extra_recipe_row(
    matrix_info,
    recipe_name,
    synthetic_index
)
    -- If the recipe somehow already made it into the cost matrix, there is
    -- nothing to add.  Avoid a duplicate row because it can create unnecessary
    -- degeneracy in the flow solution.
    if matrix_contains_recipe(matrix_info, recipe_name) then
        return nil
    end

    local recipe = data.raw.recipe[recipe_name]
    if recipe == nil then
        error(
            "Could not find blocked science pack recipe "
            .. tostring(recipe_name)
            .. " for flow-only augmentation"
        )
    end

    local net_row = {}
    local ingredient_row = {}
    local result_row = {}

    add_recipe_entries_to_rows(
        recipe.ingredients,
        -1,
        net_row,
        ingredient_row,
        matrix_info
    )
    add_recipe_entries_to_rows(
        recipe.results,
        1,
        net_row,
        result_row,
        matrix_info
    )

    local additional_cost =
        constants.simplex_per_recipe_cost
        + (recipe.energy_required or 0.5)
        * constants.simplex_per_second_cost

    return {
        index = synthetic_index,
        cost = additional_cost,
        coeffs = sparse_row_to_coeff_pairs(net_row),
        source_type = "recipe",
        source_name = recipe.name,
        gross_ingredients = sparse_gross_row_to_entries(
            ingredient_row,
            matrix_info.material_list
        ),
        gross_products = sparse_gross_row_to_entries(
            result_row,
            matrix_info.material_list
        ),
        flow_only = true,
    }
end

local function emit_chunked_json(json_string)
    log("PROPERTYRANDOMIZER_LP_JSON_BEGIN")

    local pos = 1
    while pos <= string.len(json_string) do
        log(
            "PROPERTYRANDOMIZER_LP_JSON_CHUNK "
            .. string.sub(json_string, pos, pos + CHUNK_SIZE - 1)
        )
        pos = pos + CHUNK_SIZE
    end

    log("PROPERTYRANDOMIZER_LP_JSON_END")
end

local function requirement_name_amount(requirement)
    local name = requirement.name or requirement[1]
    local amount = requirement.amount or requirement[2] or 1

    if name == nil then
        error("Science requirement has no name")
    end

    return name, tonumber(amount)
end

local function build_material_metadata(matrix_info)
    local materials = {}
    local item_name_to_metadata = {}

    for index, material in pairs(matrix_info.material_list) do
        local metadata = {
            index = index,
            key = gutils.key(material),
            type = material.type,
            name = material.name,
        }

        materials[#materials + 1] = metadata

        if material.type == "item" then
            item_name_to_metadata[material.name] = metadata
        end
    end

    table.sort(materials, function(a, b)
        return a.index < b.index
    end)

    return materials, item_name_to_metadata
end

local function normalize_requirements(requirements, item_name_to_metadata)
    local normalized = {}

    for _, requirement in pairs(requirements or {}) do
        local name, amount = requirement_name_amount(requirement)
        local material = item_name_to_metadata[name]

        if material == nil then
            error(
                "Science pack " .. tostring(name)
                .. " is missing from material_list"
            )
        end

        normalized[#normalized + 1] = {
            name = name,
            amount = amount,
            material_index = material.index,
            key = material.key,
        }
    end

    table.sort(normalized, function(a, b)
        return a.material_index < b.material_index
    end)

    return normalized
end

local function requirements_from_technology(
    technology_name,
    item_name_to_metadata
)
    local technology = data.raw.technology[technology_name]

    if technology == nil then
        error(
            "Could not find technology " .. tostring(technology_name)
            .. " while building science target"
        )
    end

    if technology.unit == nil or technology.unit.ingredients == nil then
        error(
            "Technology " .. tostring(technology_name)
            .. " has no unit.ingredients"
        )
    end

    return normalize_requirements(
        technology.unit.ingredients,
        item_name_to_metadata
    )
end

local function parse_options(stage_or_options)
    local options = {}

    if type(stage_or_options) == "number" then
        options.stage_index = stage_or_options
        options.is_pyanodons = true
    elseif type(stage_or_options) == "table" then
        for k, v in pairs(stage_or_options) do
            options[k] = v
        end
    elseif stage_or_options ~= nil then
        error(
            "export_to_log second argument must be nil, a Py stage number, "
            .. "or an options table"
        )
    end

    if options.is_pyanodons == nil then
        options.is_pyanodons = detect_pyanodons()
    end

    if options.staged_costs == nil then
        options.staged_costs = options.is_pyanodons
    end

    return options
end

local function build_py_science_metadata(
    matrix_info,
    item_name_to_metadata,
    options
)
    local stage_index = options.stage_index

    if stage_index == nil then
        error(
            "Pyanodons staged export requires stage_index "
            .. "(1.." .. tostring(PY_STAGE_COUNT) .. ")"
        )
    end

    if stage_index < 1 or stage_index > PY_STAGE_COUNT then
        error(
            "Pyanodons stage_index must be 1.."
            .. tostring(PY_STAGE_COUNT)
            .. ", got " .. tostring(stage_index)
        )
    end

    if stage_index <= #PY_PACKS_IN_ORDER then
        if matrix_info.pack_level_to_packs == nil then
            error(
                "Pyanodons staged export needs "
                .. "matrix_info.pack_level_to_packs"
            )
        end

        local raw_requirements =
            matrix_info.pack_level_to_packs[stage_index]

        if raw_requirements == nil then
            error(
                "pack_level_to_packs is missing Py stage "
                .. tostring(stage_index)
                .. " (" .. PY_PACKS_IN_ORDER[stage_index] .. ")"
            )
        end

        local requirements = normalize_requirements(
            raw_requirements,
            item_name_to_metadata
        )

        local has_current_pack = false
        for _, req in ipairs(requirements) do
            if req.name == PY_PACKS_IN_ORDER[stage_index] then
                has_current_pack = true
                break
            end
        end

        if not has_current_pack then
            error(
                "Py stage " .. tostring(stage_index)
                .. " requirements do not contain expected pack "
                .. PY_PACKS_IN_ORDER[stage_index]
            )
        end

        return {
            mode = "pyanodons-staged",
            is_pyanodons = true,
            staged_costs = true,
            stage_index = stage_index,
            stage_count = PY_STAGE_COUNT,
            stage_name = "pre-" .. PY_PACKS_IN_ORDER[stage_index],
            blocked_pack = PY_PACKS_IN_ORDER[stage_index],
            current = {
                name = PY_PACKS_IN_ORDER[stage_index],
                stage_index = stage_index,
                requirements = requirements,
            },
            py_packs_in_order = PY_PACKS_IN_ORDER,
        }
    end

    -- Final unrestricted Py matrix. Still calculate material costs for this
    -- stage, but there is deliberately no science target / flow / loop solve.
    return {
        mode = "pyanodons-staged",
        is_pyanodons = true,
        staged_costs = true,
        stage_index = stage_index,
        stage_count = PY_STAGE_COUNT,
        stage_name = "full-pyrrhic-victory",
        blocked_pack = nil,
        current = nil,
        py_packs_in_order = PY_PACKS_IN_ORDER,
    }
end

local function build_generic_science_metadata(
    item_name_to_metadata,
    options
)
    local current = nil

    if options.requirements ~= nil then
        current = {
            name = options.name or "generic-science-bundle",
            requirements = normalize_requirements(
                options.requirements,
                item_name_to_metadata
            ),
        }
    elseif options.technology ~= nil then
        current = {
            name = options.name or options.technology,
            source_technology = options.technology,
            requirements = requirements_from_technology(
                options.technology,
                item_name_to_metadata
            ),
        }
    end

    return {
        mode = "generic",
        is_pyanodons = false,
        staged_costs = false,
        current = current,
    }
end

function simplex_lp_export.build_export_object(
    sort_info,
    stage_or_options
)
    local options = parse_options(stage_or_options)

    local matrix_info =
        simplex_cost.make_recipe_material_matrix(sort_info)

    local materials, item_name_to_metadata =
        build_material_metadata(matrix_info)

    local science
    if options.is_pyanodons then
        science = build_py_science_metadata(
            matrix_info,
            item_name_to_metadata,
            options
        )
    else
        science = build_generic_science_metadata(
            item_name_to_metadata,
            options
        )
    end

    local rows = {}

    for row_index, row in pairs(matrix_info.matrix) do
        local source = matrix_info.row_sources[row_index]
        if source == nil then
            error("Missing row source for row " .. tostring(row_index))
        end

        local gross_ingredients = {}
        local gross_products = {}

        if source.type == "recipe" then
            local ingredient_row =
                matrix_info.recipe_ingredient_amounts
                and matrix_info.recipe_ingredient_amounts[row_index]
            local result_row =
                matrix_info.recipe_result_amounts
                and matrix_info.recipe_result_amounts[row_index]

            if ingredient_row == nil or result_row == nil then
                error(
                    "Recipe row " .. tostring(row_index)
                    .. " (" .. tostring(source.name)
                    .. ") is missing gross ingredient/result rows"
                )
            end

            gross_ingredients = sparse_gross_row_to_entries(
                ingredient_row,
                matrix_info.material_list
            )
            gross_products = sparse_gross_row_to_entries(
                result_row,
                matrix_info.material_list
            )
        end

        rows[#rows + 1] = {
            index = row_index,
            cost = matrix_info.cost_column[row_index],
            coeffs = sparse_row_to_coeff_pairs(row),
            source_type = source.type,
            source_name = source.name,
            gross_ingredients = gross_ingredients,
            gross_products = gross_products,
        }
    end

    table.sort(rows, function(a, b)
        return a.index < b.index
    end)

    -- For Py stages before the final unrestricted matrix, add back ONLY the
    -- currently blocked science-pack recipe for the science-flow LP.
    --
    -- This is deliberately stored outside `rows`, so it can never affect the
    -- staged per-material cost calculations.
    science.flow_extra_rows = {}

    if science.is_pyanodons
        and science.current ~= nil
        and science.blocked_pack ~= nil
    then
        local extra_row = build_flow_extra_recipe_row(
            matrix_info,
            science.blocked_pack,
            #matrix_info.matrix + 1
        )

        if extra_row ~= nil then
            science.flow_extra_rows[1] = extra_row
        end
    end

    return {
        format = "propertyrandomizer-lp-v3",
        lua_indexed = true,

        description = {
            variables = "material prices p[j]",
            objective = "for each target material t, maximize p[t]",
            constraints = "A p <= b, p >= 0",
            row_coefficients =
                "positive = net produced, negative = net consumed",
            gross_io =
                "gross recipe inputs/outputs before cancellation; "
                .. "used for active-plan operational loop detection",
            flow_extra_rows =
                "flow-only current science recipe rows are stored under "
                .. "science.flow_extra_rows and never affect material costs",
        },

        run = {
            mode = science.mode,
            is_pyanodons = science.is_pyanodons,
            staged_costs = science.staged_costs,
        },

        science = science,

        num_materials = #matrix_info.material_list,
        num_rows = #matrix_info.matrix,
        materials = materials,
        rows = rows,
    }
end

function simplex_lp_export.export_to_log(
    sort_info,
    stage_or_options
)
    local export_object = simplex_lp_export.build_export_object(
        sort_info,
        stage_or_options
    )

    local json_string = json_encode(export_object)

    local current = export_object.science.current

    log(
        "Exporting simplex LP JSON"
        .. " mode=" .. tostring(export_object.run.mode)
        .. " staged_costs="
        .. tostring(export_object.run.staged_costs)
        .. " stage="
        .. tostring(export_object.science.stage_name or "generic")
        .. " science="
        .. tostring(current and current.name or "none")
        .. " materials=" .. tostring(export_object.num_materials)
        .. " rows=" .. tostring(export_object.num_rows)
        .. " chars=" .. tostring(string.len(json_string))
    )

    emit_chunked_json(json_string)
end

return simplex_lp_export