#!/usr/bin/env python3
# generated by chatGPT

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix


BEGIN_MARKER = "PROPERTYRANDOMIZER_LP_JSON_BEGIN"
CHUNK_MARKER = "PROPERTYRANDOMIZER_LP_JSON_CHUNK "
END_MARKER = "PROPERTYRANDOMIZER_LP_JSON_END"


def extract_lp_json_text(path: Path) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")

    stripped = text.lstrip()
    if stripped.startswith("{"):
        return stripped

    chunks: list[str] = []
    inside = False

    for line in text.splitlines():
        if BEGIN_MARKER in line:
            chunks = []
            inside = True
            continue

        if END_MARKER in line and inside:
            inside = False
            break

        if inside:
            idx = line.find(CHUNK_MARKER)
            if idx >= 0:
                chunks.append(line[idx + len(CHUNK_MARKER):])

    if not chunks:
        raise RuntimeError(
            f"Could not find chunked LP JSON in {path}. "
            f"Expected markers {BEGIN_MARKER!r} and {CHUNK_MARKER!r}."
        )

    return "".join(chunks)


def load_lp(path: Path) -> dict:
    json_text = extract_lp_json_text(path)
    lp = json.loads(json_text)

    if lp.get("format") != "propertyrandomizer-lp-v1":
        raise RuntimeError(f"Unexpected LP format: {lp.get('format')!r}")

    return lp


def build_sparse_matrix(lp: dict):
    num_materials = int(lp["num_materials"])
    num_rows = int(lp["num_rows"])

    row_indices = []
    col_indices = []
    data = []
    b = np.zeros(num_rows, dtype=float)

    for row_obj in lp["rows"]:
        row_index_lua = int(row_obj["index"])
        row_index = row_index_lua - 1

        b[row_index] = float(row_obj["cost"])

        for col_lua, value in row_obj["coeffs"]:
            col = int(col_lua) - 1
            row_indices.append(row_index)
            col_indices.append(col)
            data.append(float(value))

    A = coo_matrix(
        (np.array(data, dtype=float), (row_indices, col_indices)),
        shape=(num_rows, num_materials),
    ).tocsr()

    return A, b


def solve_one_target(A, b, target_index_zero_based: int, method: str):
    n = A.shape[1]
    c = np.zeros(n, dtype=float)
    c[target_index_zero_based] = -1.0

    result = linprog(
        c,
        A_ub=A,
        b_ub=b,
        bounds=(0, None),
        method=method,
        options={
            "presolve": True,
        },
    )

    if result.status == 0:
        return {
            "status": "optimal",
            "objective": float(-result.fun),
            "message": result.message,
            "nit": getattr(result, "nit", None),
        }

    if result.status == 3:
        return {
            "status": "unbounded",
            "objective": None,
            "message": result.message,
            "nit": getattr(result, "nit", None),
        }

    if result.status == 2:
        return {
            "status": "infeasible",
            "objective": None,
            "message": result.message,
            "nit": getattr(result, "nit", None),
        }

    return {
        "status": f"solver_status_{result.status}",
        "objective": None,
        "message": result.message,
        "nit": getattr(result, "nit", None),
    }


def parse_targets(lp: dict, targets_arg: str | None):
    materials = lp["materials"]

    if not targets_arg:
        return [int(m["index"]) for m in materials]

    key_to_index = {m["key"]: int(m["index"]) for m in materials}
    name_to_indices = {}
    for m in materials:
        name_to_indices.setdefault(m["name"], []).append(int(m["index"]))

    targets = []

    for token in targets_arg.split(","):
        token = token.strip()
        if not token:
            continue

        if token.isdigit():
            targets.append(int(token))
        elif token in key_to_index:
            targets.append(key_to_index[token])
        elif token in name_to_indices and len(name_to_indices[token]) == 1:
            targets.append(name_to_indices[token][0])
        else:
            raise RuntimeError(
                f"Could not resolve target {token!r}. "
                f"Use a Lua index, material key like 'item/iron-plate', "
                f"or an unambiguous material name."
            )

    return targets


def lua_quote(s: str) -> str:
    return json.dumps(s)


def write_lua_result(path: Path, lp: dict, results: dict):
    materials_by_index = {int(m["index"]): m for m in lp["materials"]}

    lines = []
    lines.append("-- generated by chatGPT")
    lines.append("return {")
    lines.append("    metadata = {")
    lines.append(f"        format = {lua_quote('propertyrandomizer-material-costs-v1')},")
    lines.append(f"        source_format = {lua_quote(lp.get('format', 'unknown'))},")
    lines.append(f"        num_materials = {int(lp['num_materials'])},")
    lines.append(f"        num_rows = {int(lp['num_rows'])},")
    lines.append("    },")
    lines.append("    costs = {")

    for index in sorted(results.keys(), key=int):
        result = results[index]
        material = materials_by_index[int(index)]
        key = material["key"]
        objective = result["objective"]

        if objective is not None and math.isfinite(objective):
            lines.append(f"        [{lua_quote(key)}] = {objective:.17g},")

    lines.append("    },")
    lines.append("    statuses = {")

    for index in sorted(results.keys(), key=int):
        result = results[index]
        material = materials_by_index[int(index)]
        key = material["key"]
        status = result["status"]
        lines.append(f"        [{lua_quote(key)}] = {lua_quote(status)},")

    lines.append("    },")
    lines.append("}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(
        description="Solve a PropertyRandomizer exported material-cost LP."
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Factorio log containing chunked LP JSON, or a raw LP JSON file.",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=Path("material_costs.json"),
        help="Output JSON result file.",
    )
    parser.add_argument(
        "--out-lua",
        type=Path,
        default=Path("material-costs.lua"),
        help="Output Lua table result file.",
    )
    parser.add_argument(
        "--method",
        default="highs",
        choices=["highs", "highs-ds", "highs-ipm"],
        help="SciPy linprog HiGHS method.",
    )
    parser.add_argument(
        "--targets",
        default=None,
        help=(
            "Comma-separated targets to solve. Each target may be a Lua index, "
            "a key like item/iron-plate, or an unambiguous material name. "
            "Default: solve all materials."
        ),
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Solve only the first N selected targets, useful for testing.",
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=25,
        help="Print progress every N solves.",
    )

    args = parser.parse_args()

    lp = load_lp(args.input)
    A, b = build_sparse_matrix(lp)

    print(f"Loaded LP: rows={A.shape[0]} materials={A.shape[1]} nnz={A.nnz}")

    targets = parse_targets(lp, args.targets)
    if args.limit is not None:
        targets = targets[: args.limit]

    materials_by_index = {int(m["index"]): m for m in lp["materials"]}

    results = {}

    for k, target_lua_index in enumerate(targets, start=1):
        target_zero = target_lua_index - 1
        material = materials_by_index[target_lua_index]

        if k == 1 or k % args.progress_every == 0:
            print(
                f"[{k}/{len(targets)}] solving "
                f"{material['key']} index={target_lua_index}",
                flush=True,
            )

        result = solve_one_target(A, b, target_zero, args.method)
        results[str(target_lua_index)] = result

        if result["status"] != "optimal":
            print(
                f"  status={result['status']} "
                f"message={result['message']}",
                flush=True,
            )

    output = {
        "format": "propertyrandomizer-material-costs-v1",
        "source": {
            "format": lp.get("format"),
            "num_materials": lp.get("num_materials"),
            "num_rows": lp.get("num_rows"),
            "nnz": int(A.nnz),
        },
        "results_by_lua_index": results,
        "costs": {},
        "statuses": {},
    }

    for index_str, result in results.items():
        material = materials_by_index[int(index_str)]
        key = material["key"]

        if result["objective"] is not None:
            output["costs"][key] = result["objective"]

        output["statuses"][key] = result["status"]

    args.out_json.write_text(
        json.dumps(output, indent=2, sort_keys=True),
        encoding="utf-8",
    )

    write_lua_result(args.out_lua, lp, results)

    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_lua}")


if __name__ == "__main__":
    main()