# Generated by ChatGPT
# This file is only used for cost table creation and not run on game startup

#!/usr/bin/env python3
"""
PropertyRandomizer multi-level LP solver.

Pyanodons:
  * stages 1..10:
      - science production flow + operational loops first
      - one staged material-cost table per matrix
  * final unrestricted stage:
      - no science/loop analysis
      - still gets its own staged material-cost table

Generic / Space Age:
  * no science production-flow calculation
  * no loop calculation
  * no staged material costs
  * only the LAST/full exported matrix gets a material-cost table

Material cost files default to:
    material-costs/py-full-automation-science.json
    material-costs/py-full-automation-science.lua
    material-costs/py-full-py-science-1.json
    ...

Science-flow code lives separately in science_flow.py.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix

from science_flow import (
    analyze_operational_loops,
    has_science_target,
    solve_science_flow,
    write_loops_lua,
)


BEGIN_MARKER = "PROPERTYRANDOMIZER_LP_JSON_BEGIN"
CHUNK_MARKER = "PROPERTYRANDOMIZER_LP_JSON_CHUNK "
END_MARKER = "PROPERTYRANDOMIZER_LP_JSON_END"


# ---------------------------------------------------------------------------
# Export parsing
# ---------------------------------------------------------------------------

def extract_all_lp_objects(path: Path) -> list[dict[str, Any]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    stripped = text.lstrip()

    if stripped.startswith("{"):
        objects = [json.loads(stripped)]
    else:
        objects: list[dict[str, Any]] = []
        chunks: list[str] = []
        inside = False

        for line in text.splitlines():
            if BEGIN_MARKER in line:
                if inside:
                    raise RuntimeError("Nested LP BEGIN markers")
                inside = True
                chunks = []
                continue

            if not inside:
                continue

            pos = line.find(CHUNK_MARKER)
            if pos >= 0:
                chunks.append(line[pos + len(CHUNK_MARKER):])
                continue

            if END_MARKER in line:
                if not chunks:
                    raise RuntimeError(
                        "LP export ended without JSON chunks"
                    )
                objects.append(json.loads("".join(chunks)))
                chunks = []
                inside = False

        if inside:
            raise RuntimeError("Log ended inside an LP export")

    if not objects:
        raise RuntimeError("No PropertyRandomizer LP exports found")

    for ordinal, lp in enumerate(objects, start=1):
        if lp.get("format") != "propertyrandomizer-lp-v3":
            raise RuntimeError(
                f"Export {ordinal}: expected propertyrandomizer-lp-v3, "
                f"got {lp.get('format')!r}"
            )

    return objects


def build_sparse_matrix(lp: dict[str, Any]):
    n_materials = int(lp["num_materials"])
    n_rows = int(lp["num_rows"])

    rr: list[int] = []
    cc: list[int] = []
    vv: list[float] = []
    b = np.zeros(n_rows, dtype=float)

    for row in lp["rows"]:
        row_zero = int(row["index"]) - 1
        b[row_zero] = float(row["cost"])

        for lua_col, coefficient in row["coeffs"]:
            rr.append(row_zero)
            cc.append(int(lua_col) - 1)
            vv.append(float(coefficient))

    A = coo_matrix(
        (vv, (rr, cc)),
        shape=(n_rows, n_materials),
    ).tocsr()

    return A, b


def run_info(lp: dict[str, Any]) -> dict[str, Any]:
    return lp.get("run") or {}


def is_pyanodons(lp: dict[str, Any]) -> bool:
    return bool(run_info(lp).get("is_pyanodons"))


def staged_costs(lp: dict[str, Any]) -> bool:
    return bool(run_info(lp).get("staged_costs"))


# ---------------------------------------------------------------------------
# Output naming
# ---------------------------------------------------------------------------

def _pack_to_old_style_name(pack: str) -> str:
    """
    Match the old material-cost filenames shown by the user.

      automation-science-pack -> automation-science
      py-science-pack-1       -> py-science-1
      production-science-pack -> production-science
    """
    if pack.startswith("py-science-pack-"):
        return "py-science-" + pack.removeprefix("py-science-pack-")

    if pack.endswith("-science-pack"):
        return pack.removesuffix("-pack")

    return pack


def py_stage_basename(lp: dict[str, Any]) -> str:
    science = lp.get("science") or {}
    stage_index = science.get("stage_index")
    stage_count = science.get("stage_count")
    current = science.get("current") or {}

    # Final unrestricted Py matrix.
    if (
        stage_index is not None
        and stage_count is not None
        and int(stage_index) == int(stage_count)
        and not current
    ):
        return "py-full-pyrrhic-victory"

    pack = science.get("blocked_pack") or current.get("name")

    if not pack:
        raise RuntimeError(
            "Could not determine Py stage filename from science metadata"
        )

    return "py-full-" + _pack_to_old_style_name(str(pack))


def material_cost_basename(
    lp: dict[str, Any],
    generic_basename: str,
) -> str:
    if is_pyanodons(lp):
        return py_stage_basename(lp)

    return generic_basename


def flow_basename(lp: dict[str, Any]) -> str:
    # Use exactly the same stage stem as the corresponding material costs.
    return py_stage_basename(lp)


# ---------------------------------------------------------------------------
# Material costs
# ---------------------------------------------------------------------------

def solve_one_material(
    A,
    b: np.ndarray,
    rows: list[dict[str, Any]],
    target_zero: int,
    method: str,
) -> dict[str, Any]:
    c = np.zeros(A.shape[1], dtype=float)
    c[target_zero] = -1.0

    result = linprog(
        c=c,
        A_ub=A,
        b_ub=b,
        bounds=(0, None),
        method=method,
        options={"presolve": True},
    )

    if result.status != 0:
        status = (
            "unbounded" if result.status == 3
            else "infeasible" if result.status == 2
            else f"solver_status_{result.status}"
        )

        return {
            "status": status,
            "objective": None,
            "recipe": None,
            "producer": None,
            "message": result.message,
            "nit": getattr(result, "nit", None),
        }

    # Primal row activities corresponding to this dual optimum.
    marginals = np.asarray(
        result.ineqlin.marginals,
        dtype=float,
    )
    row_usages = np.maximum(0.0, -marginals)

    producer = None
    best_contribution = 0.0

    for row in rows:
        row_zero = int(row["index"]) - 1
        target_output = float(A[row_zero, target_zero])

        if target_output <= 0.0:
            continue

        usage = float(row_usages[row_zero])
        contribution = usage * target_output

        if contribution <= 1e-9:
            continue

        if contribution > best_contribution:
            best_contribution = contribution
            producer = {
                "row_index": int(row["index"]),
                "source_type": row.get("source_type"),
                "source_name": row.get("source_name"),
                "usage": usage,
                "target_output_per_use": target_output,
                "target_contribution": contribution,
            }

    recipe = (
        producer["source_name"]
        if producer is not None
        and producer.get("source_type") == "recipe"
        else None
    )

    return {
        "status": "optimal",
        "objective": float(-result.fun),
        "recipe": recipe,
        "producer": producer,
        "message": result.message,
        "nit": getattr(result, "nit", None),
    }


def solve_all_materials(
    A,
    b: np.ndarray,
    lp: dict[str, Any],
    method: str,
    progress_every: int,
) -> dict[str, Any]:
    materials = {
        int(material["index"]): material
        for material in lp["materials"]
    }

    indices = sorted(materials)
    results: dict[str, Any] = {}

    for ordinal, material_index in enumerate(indices, start=1):
        if (
            ordinal == 1
            or ordinal % progress_every == 0
            or ordinal == len(indices)
        ):
            print(
                f"    [{ordinal}/{len(indices)}] "
                f"{materials[material_index]['key']}",
                flush=True,
            )

        results[str(material_index)] = solve_one_material(
            A=A,
            b=b,
            rows=lp["rows"],
            target_zero=material_index - 1,
            method=method,
        )

    return results


# ---------------------------------------------------------------------------
# Material-cost outputs
# ---------------------------------------------------------------------------

def _lua_quote(value: str) -> str:
    return json.dumps(value)


def write_material_json(
    path: Path,
    lp: dict[str, Any],
    A,
    results: dict[str, Any],
) -> None:
    materials = {
        int(material["index"]): material
        for material in lp["materials"]
    }

    output: dict[str, Any] = {
        "format": "propertyrandomizer-material-costs-v3",
        "source": {
            "format": lp.get("format"),
            "run": lp.get("run"),
            "science": lp.get("science"),
            "num_materials": int(lp["num_materials"]),
            "num_rows": int(lp["num_rows"]),
            "nnz": int(A.nnz),
        },
        "results_by_lua_index": results,
        "costs": {},
        "recipes": {},
        "statuses": {},
    }

    for index_text, result in results.items():
        key = materials[int(index_text)]["key"]

        if result.get("objective") is not None:
            output["costs"][key] = result["objective"]

        if result.get("recipe") is not None:
            output["recipes"][key] = result["recipe"]

        output["statuses"][key] = result["status"]

    path.write_text(
        json.dumps(output, indent=2, sort_keys=True),
        encoding="utf-8",
    )


def write_material_lua(
    path: Path,
    lp: dict[str, Any],
    results: dict[str, Any],
) -> None:
    materials = {
        int(material["index"]): material
        for material in lp["materials"]
    }

    lines = [
        "-- generated by solve_lp_levels.py",
        "return {",
        "    metadata = {",
        '        format = "propertyrandomizer-material-costs-v3",',
        f"        source_format = "
        f"{_lua_quote(str(lp.get('format')))},",
        f"        is_pyanodons = "
        f"{str(is_pyanodons(lp)).lower()},",
        f"        staged_costs = "
        f"{str(staged_costs(lp)).lower()},",
        f"        num_materials = {int(lp['num_materials'])},",
        f"        num_rows = {int(lp['num_rows'])},",
        "    },",
        "    costs = {",
    ]

    for index_text in sorted(results, key=int):
        result = results[index_text]
        value = result.get("objective")

        if value is None or not math.isfinite(float(value)):
            continue

        key = materials[int(index_text)]["key"]
        lines.append(
            f"        [{_lua_quote(key)}] = {float(value):.17g},"
        )

    lines.extend(["    },", "    statuses = {"])

    for index_text in sorted(results, key=int):
        key = materials[int(index_text)]["key"]
        lines.append(
            f"        [{_lua_quote(key)}] = "
            f"{_lua_quote(results[index_text]['status'])},"
        )

    lines.extend(["    },", "    recipes = {"])

    for index_text in sorted(results, key=int):
        recipe = results[index_text].get("recipe")
        if recipe is None:
            continue

        key = materials[int(index_text)]["key"]
        lines.append(
            f"        [{_lua_quote(key)}] = {_lua_quote(recipe)},"
        )

    lines.extend(["    },", "}"])

    path.write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Run validation
# ---------------------------------------------------------------------------

def validate_and_select_cost_stages(stages):
    flags = {
        (is_pyanodons(lp), staged_costs(lp))
        for _, lp, _, _ in stages
    }

    if len(flags) != 1:
        raise RuntimeError(
            "The log mixes incompatible Py/generic export modes. "
            "Use a separate log for each run."
        )

    py_mode, staged = flags.pop()

    if py_mode:
        if not staged:
            raise RuntimeError(
                "Pyanodons export says staged_costs=false"
            )

        stage_indices: list[int] = []

        for ordinal, lp, _, _ in stages:
            science = lp.get("science") or {}
            stage_index = science.get("stage_index")

            if stage_index is None:
                raise RuntimeError(
                    f"Py export {ordinal} has no science.stage_index"
                )

            stage_indices.append(int(stage_index))

        if stage_indices != sorted(stage_indices):
            raise RuntimeError(
                f"Py stages are out of order: {stage_indices}"
            )

        if len(set(stage_indices)) != len(stage_indices):
            raise RuntimeError(
                f"Duplicate Py stages: {stage_indices}"
            )

        declared_counts = {
            int((lp.get("science") or {}).get("stage_count"))
            for _, lp, _, _ in stages
            if (lp.get("science") or {}).get("stage_count") is not None
        }

        if len(declared_counts) == 1:
            declared_count = declared_counts.pop()
            if stage_indices[-1] != declared_count:
                raise RuntimeError(
                    f"Last Py export is stage {stage_indices[-1]}, "
                    f"but exporter declares {declared_count} stages"
                )

        return True, stages

    # Generic/Space Age: never do staged cost calculation.  If more than one
    # generic matrix was printed, only the last/full one gets material costs.
    if staged:
        raise RuntimeError(
            "Generic export unexpectedly has staged_costs=true"
        )

    if len(stages) > 1:
        print(
            f"WARNING: found {len(stages)} generic exports; "
            "only the LAST one will receive material costs.",
            flush=True,
        )

    return False, [stages[-1]]


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "input",
        type=Path,
        help="Factorio log containing the LP export(s)",
    )
    parser.add_argument(
        "--material-cost-dir",
        type=Path,
        default=Path("material-costs"),
        help="Output folder for material cost .json/.lua files",
    )
    parser.add_argument(
        "--flow-dir",
        type=Path,
        default=Path("science-flows"),
        help="Output folder for Py science-flow/loop files",
    )
    parser.add_argument(
        "--generic-basename",
        default="full",
        help=(
            "Basename for the single generic/Space Age material-cost "
            "table (default: full)"
        ),
    )
    parser.add_argument(
        "--method",
        choices=["highs", "highs-ds", "highs-ipm"],
        default="highs",
    )
    parser.add_argument(
        "--max-cycle-length",
        type=int,
        default=10,
    )
    parser.add_argument(
        "--plan-eps",
        type=float,
        default=1e-9,
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=25,
    )
    parser.add_argument(
        "--science-only",
        action="store_true",
        help=(
            "Run Py science-flow/loop analysis and stop before "
            "material-cost solving"
        ),
    )

    args = parser.parse_args()

    args.material_cost_dir.mkdir(
        parents=True,
        exist_ok=True,
    )
    args.flow_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    lps = extract_all_lp_objects(args.input)

    stages = []
    for ordinal, lp in enumerate(lps, start=1):
        A, b = build_sparse_matrix(lp)
        stages.append((ordinal, lp, A, b))

    py_mode, cost_stages = validate_and_select_cost_stages(
        stages
    )

    print(
        f"Found {len(stages)} LP export(s); "
        f"mode={'pyanodons-staged' if py_mode else 'generic'}",
        flush=True,
    )

    # ---------------------------------------------------------------
    # PHASE 1: Py science production flows + loops.
    # Generic/Space Age deliberately never runs this algorithm.
    # ---------------------------------------------------------------

    if py_mode:
        targeted = [
            stage
            for stage in stages
            if has_science_target(stage[1])
        ]

        if targeted:
            print(
                "\n===== PHASE 1: PY SCIENCE FLOWS + LOOPS =====",
                flush=True,
            )

        for ordinal, lp, A, b in targeted:
            basename = flow_basename(lp)

            print(
                f"\n=== {basename} science flow ===",
                flush=True,
            )

            flow = solve_science_flow(
                A=A,
                b=b,
                lp=lp,
                method=args.method,
                active_eps=args.plan_eps,
            )

            flow_path = (
                args.flow_dir / f"{basename}-flow.json"
            )
            flow_path.write_text(
                json.dumps(flow, indent=2, sort_keys=True),
                encoding="utf-8",
            )

            loops = analyze_operational_loops(
                lp=lp,
                flow=flow,
                max_cycle_length=args.max_cycle_length,
            )

            loops_json = (
                args.flow_dir / f"{basename}-loops.json"
            )
            loops_lua = (
                args.flow_dir / f"{basename}-loops.lua"
            )

            loops_json.write_text(
                json.dumps(loops, indent=2, sort_keys=True),
                encoding="utf-8",
            )
            write_loops_lua(
                loops_lua,
                loops,
            )

            stats = loops.get("stats") or {}

            print(
                f"  flow status={flow['status']} "
                f"cost={flow.get('objective')}",
                flush=True,
            )
            print(
                "  protected edges="
                f"{stats.get('protected_recipe_ingredient_edges', 0)} "
                "by length="
                f"{stats.get('protected_by_min_cycle_length', {})}",
                flush=True,
            )
            print(f"  wrote {flow_path}", flush=True)
            print(f"  wrote {loops_json}", flush=True)
            print(f"  wrote {loops_lua}", flush=True)

    if args.science_only:
        if not py_mode:
            print(
                "--science-only requested in generic mode; "
                "there is no science-flow phase.",
                flush=True,
            )
        return

    # ---------------------------------------------------------------
    # PHASE 2: material costs.
    # All Py snapshots; only final/full snapshot for generic mode.
    # ---------------------------------------------------------------

    print(
        "\n===== PHASE 2: MATERIAL COSTS =====",
        flush=True,
    )

    for ordinal, lp, A, b in cost_stages:
        basename = material_cost_basename(
            lp,
            args.generic_basename,
        )

        print(
            f"\n=== {basename} ===",
            flush=True,
        )

        results = solve_all_materials(
            A=A,
            b=b,
            lp=lp,
            method=args.method,
            progress_every=args.progress_every,
        )

        json_path = (
            args.material_cost_dir / f"{basename}.json"
        )
        lua_path = (
            args.material_cost_dir / f"{basename}.lua"
        )

        write_material_json(
            json_path,
            lp,
            A,
            results,
        )
        write_material_lua(
            lua_path,
            lp,
            results,
        )

        print(f"  wrote {json_path}", flush=True)
        print(f"  wrote {lua_path}", flush=True)


if __name__ == "__main__":
    main()
