-- generated by chatGPT

local SparseSimplex = {}

local DEFAULT_EPS = 1e-13
local DEFAULT_FEAS_EPS = 1e-7
local DEFAULT_MONOTONE_EPS = 1e-7
local DEFAULT_RATIO_EPS = 1e-12
local DEFAULT_LOG_INTERVAL = 100
local DEFAULT_MAX_PIVOTS = 100000

-- Approximation defaults.
-- These are intentionally enabled by default because this solver is being used
-- as a cost heuristic, not as a certified LP optimizer.
local DEFAULT_APPROX = true
local DEFAULT_APPROX_MIN_PIVOTS = 1
local DEFAULT_APPROX_WINDOW = 1
local DEFAULT_APPROX_REL_IMPROVEMENT = 0.2
local DEFAULT_APPROX_ABS_IMPROVEMENT = 1e-3
local DEFAULT_APPROX_MAX_PIVOTS = 200

local function default_logger(message)
    if type(log) == "function" then
        log(message)
    end
end

local function abs(x)
    return math.abs(x)
end

local function clean_number(x, eps)
    if abs(x) < eps then
        return 0
    end

    return x
end

local function clean_rhs(x, eps, feas_eps)
    if x >= 0 then
        if x < eps then
            return 0
        end

        return x
    end

    -- Small negative RHS from numerical drift.
    if x > -feas_eps then
        return 0
    end

    -- Real negative RHS.
    return x
end

local function set_coeff(row, col, value, eps)
    if abs(value) < eps then
        row[col] = nil
    else
        row[col] = value
    end
end

local function add_coeff(row, col, delta, eps)
    set_coeff(row, col, (row[col] or 0) + delta, eps)
end

local function copy_sparse_row(row, eps)
    local out = {}

    for col, value in pairs(row) do
        if abs(value) >= eps then
            out[col] = value
        end
    end

    return out
end

local function count_nnz(row)
    local count = 0

    for _ in pairs(row) do
        count = count + 1
    end

    return count
end

local function count_column(lp, col)
    local count = 0
    local positive = 0
    local negative = 0

    for _, row in pairs(lp.rows) do
        local value = row[col]

        if value ~= nil then
            count = count + 1

            if value > lp.eps then
                positive = positive + 1
            elseif value < -lp.eps then
                negative = negative + 1
            end
        end
    end

    return count, positive, negative
end

local function choose_entering_col_most_negative(objective, eps)
    local best_col = nil
    local best_value = -eps

    for col, value in pairs(objective) do
        if value < best_value then
            best_value = value
            best_col = col
        end
    end

    return best_col, best_value
end

-- Harris-style ratio test.
--
-- First computes a relaxed maximum step that preserves feasibility up to
-- lp.feas_eps. Then chooses a numerically stable leaving row among eligible
-- candidates, preferring a larger pivot coefficient.
local function choose_leaving_row(lp, entering_col)
    local theta_max = math.huge

    -- First pass: relaxed feasibility bound.
    for i, row in pairs(lp.rows) do
        local rhs_i = lp.rhs[i]

        if rhs_i < -lp.feas_eps then
            return nil, nil, {
                status = "infeasible_basis",
                row = i,
                rhs = rhs_i,
                entering_col = entering_col,
            }
        elseif rhs_i < 0 then
            rhs_i = 0
            lp.rhs[i] = 0
        end

        local coeff = row[entering_col]

        if coeff ~= nil and coeff > lp.eps then
            local relaxed_ratio = (rhs_i + lp.feas_eps) / coeff

            if relaxed_ratio < theta_max then
                theta_max = relaxed_ratio
            end
        end
    end

    if theta_max == math.huge then
        return nil, nil, nil -- unbounded
    end

    -- Second pass: choose a stable eligible pivot.
    local best_row = nil
    local best_ratio = nil
    local best_coeff = 0
    local candidate_count = 0

    local theta_tolerance = lp.ratio_eps * math.max(1, abs(theta_max))

    for i, row in pairs(lp.rows) do
        local rhs_i = lp.rhs[i]
        local coeff = row[entering_col]

        if coeff ~= nil and coeff > lp.eps then
            local exact_ratio = rhs_i / coeff

            if exact_ratio < 0 and exact_ratio > -lp.feas_eps then
                exact_ratio = 0
            end

            -- Important: theta_tolerance is a step-size tolerance.
            -- Do not use lp.feas_eps directly here; that is an RHS tolerance.
            if exact_ratio <= theta_max + theta_tolerance then
                candidate_count = candidate_count + 1

                if coeff > best_coeff + lp.eps then
                    best_row = i
                    best_ratio = exact_ratio
                    best_coeff = coeff
                elseif abs(coeff - best_coeff) <= lp.eps then
                    -- Tie-break by smaller exact ratio, then smaller basic variable.
                    if best_row == nil
                        or exact_ratio < best_ratio - lp.ratio_eps
                        or (
                            abs(exact_ratio - best_ratio) <= lp.ratio_eps
                            and lp.basis[i] < lp.basis[best_row]
                        )
                    then
                        best_row = i
                        best_ratio = exact_ratio
                        best_coeff = coeff
                    end
                end
            end
        end
    end

    if best_row == nil then
        return nil, nil, {
            status = "ratio_test_failed",
            entering_col = entering_col,
            theta_max = theta_max,
            candidate_count = candidate_count,
        }
    end

    return best_row, best_ratio, nil
end

local function normalize_row(row, rhs, pivot_col, eps, feas_eps)
    local pivot_value = row[pivot_col]

    if pivot_value == nil or abs(pivot_value) < eps then
        error("Cannot pivot on zero coefficient")
    end

    local to_remove = {}

    for col, value in pairs(row) do
        local new_value = value / pivot_value

        if abs(new_value) < eps then
            to_remove[#to_remove + 1] = col
        else
            row[col] = new_value
        end
    end

    for _, col in pairs(to_remove) do
        row[col] = nil
    end

    row[pivot_col] = 1

    return clean_rhs(rhs / pivot_value, eps, feas_eps)
end

local function eliminate_with_pivot(row, rhs, pivot_row, pivot_rhs, pivot_col, factor, eps, feas_eps)
    for col, pivot_value in pairs(pivot_row) do
        add_coeff(row, col, -factor * pivot_value, eps)
    end

    row[pivot_col] = nil

    return clean_rhs(rhs - factor * pivot_rhs, eps, feas_eps)
end

local function pivot(lp, pivot_row_index, pivot_col)
    local pivot_row = lp.rows[pivot_row_index]

    lp.rhs[pivot_row_index] = normalize_row(
        pivot_row,
        lp.rhs[pivot_row_index],
        pivot_col,
        lp.eps,
        lp.feas_eps
    )

    local pivot_rhs = lp.rhs[pivot_row_index]

    for i, row in pairs(lp.rows) do
        if i ~= pivot_row_index then
            local factor = row[pivot_col]

            if factor ~= nil and abs(factor) > lp.eps then
                lp.rhs[i] = eliminate_with_pivot(
                    row,
                    lp.rhs[i],
                    pivot_row,
                    pivot_rhs,
                    pivot_col,
                    factor,
                    lp.eps,
                    lp.feas_eps
                )
            end
        end
    end

    local objective_factor = lp.objective[pivot_col]

    if objective_factor ~= nil and abs(objective_factor) > lp.eps then
        for col, pivot_value in pairs(pivot_row) do
            add_coeff(lp.objective, col, -objective_factor * pivot_value, lp.eps)
        end

        lp.objective_rhs = clean_number(
            lp.objective_rhs - objective_factor * pivot_rhs,
            lp.eps
        )

        lp.objective[pivot_col] = nil
    end

    lp.basis[pivot_row_index] = pivot_col
end

local function validate_primal_feasibility(lp)
    for i, rhs_i in pairs(lp.rhs) do
        if rhs_i < -lp.feas_eps then
            return false, i, rhs_i
        elseif rhs_i < 0 then
            lp.rhs[i] = 0
        end
    end

    return true, nil, nil
end

local function should_stop_approximately(lp, pivot_count, window_start_pivot, window_start_objective)
    if not lp.approx then
        return nil
    end

    if pivot_count >= lp.approx_max_pivots and lp.objective_rhs > 0 then
        return {
            status = "approximate",
            objective = lp.objective_rhs,
            pivots = pivot_count,
            objective_nnz = count_nnz(lp.objective),
            approx_reason = "approx_max_pivots",
        }
    end

    local pivots_in_window = pivot_count - window_start_pivot

    if pivots_in_window < lp.approx_window then
        return nil
    end

    local window_delta = lp.objective_rhs - window_start_objective

    local scale = math.max(
        abs(lp.objective_rhs),
        abs(window_start_objective),
        1e-12
    )

    local rel_improvement = window_delta / scale

    if pivot_count >= lp.approx_min_pivots
        and window_delta >= 0
        and (
            rel_improvement <= lp.approx_rel_improvement
            or window_delta <= lp.approx_abs_improvement
        )
    then
        return {
            status = "approximate",
            objective = lp.objective_rhs,
            pivots = pivot_count,
            objective_nnz = count_nnz(lp.objective),
            approx_reason = "low_window_improvement",
            approx_window = lp.approx_window,
            approx_window_delta = window_delta,
            approx_rel_improvement = rel_improvement,
        }
    end

    return nil
end

function SparseSimplex.new(A, b, num_original_cols, opts)
    opts = opts or {}

    local eps = opts.eps or DEFAULT_EPS
    local feas_eps = opts.feas_eps or DEFAULT_FEAS_EPS

    local m = #A

    if #b ~= m then
        error("A and b have incompatible sizes")
    end

    local lp = {
        rows = {},
        rhs = {},
        basis = {},

        objective = {},
        objective_rhs = 0,

        m = m,
        num_original_cols = num_original_cols,
        num_total_cols = num_original_cols + m,

        eps = eps,
        feas_eps = feas_eps,
        monotone_eps = opts.monotone_eps or DEFAULT_MONOTONE_EPS,
        ratio_eps = opts.ratio_eps or DEFAULT_RATIO_EPS,

        log_interval = opts.log_interval or DEFAULT_LOG_INTERVAL,
        max_pivots = opts.max_pivots or DEFAULT_MAX_PIVOTS,
        logger = opts.logger or default_logger,

        approx = (opts.approx ~= nil) and opts.approx or DEFAULT_APPROX,
        approx_min_pivots = opts.approx_min_pivots or DEFAULT_APPROX_MIN_PIVOTS,
        approx_window = opts.approx_window or DEFAULT_APPROX_WINDOW,
        approx_rel_improvement = opts.approx_rel_improvement or DEFAULT_APPROX_REL_IMPROVEMENT,
        approx_abs_improvement = opts.approx_abs_improvement or DEFAULT_APPROX_ABS_IMPROVEMENT,
        approx_max_pivots = opts.approx_max_pivots or DEFAULT_APPROX_MAX_PIVOTS,

        current_target_col = nil,
    }

    for i = 1, m do
        if b[i] < -feas_eps then
            error("SparseSimplex requires b[i] >= 0; Phase I is not implemented")
        end

        lp.rows[i] = copy_sparse_row(A[i], eps)
        lp.rhs[i] = clean_rhs(b[i], eps, feas_eps)

        local slack_col = num_original_cols + i
        lp.rows[i][slack_col] = 1
        lp.basis[i] = slack_col
    end

    return lp
end

function SparseSimplex.set_unit_objective(lp, target_col)
    lp.objective = {}
    lp.objective_rhs = 0
    lp.current_target_col = target_col

    -- maximize x_target
    -- Tableau convention: negative reduced cost means improvement.
    lp.objective[target_col] = -1

    -- Canonicalize objective with respect to the current basis.
    for i, basic_col in pairs(lp.basis) do
        local factor = lp.objective[basic_col]

        if factor ~= nil and abs(factor) > lp.eps then
            local row = lp.rows[i]

            for col, value in pairs(row) do
                add_coeff(lp.objective, col, -factor * value, lp.eps)
            end

            lp.objective_rhs = clean_number(
                lp.objective_rhs - factor * lp.rhs[i],
                lp.eps
            )

            lp.objective[basic_col] = nil
        end
    end

    local min_coeff = 0
    local negative_count = 0

    for _, value in pairs(lp.objective) do
        if value < min_coeff then
            min_coeff = value
        end

        if value < -lp.eps then
            negative_count = negative_count + 1
        end
    end

    lp.logger(
        "Set objective"
        .. " target=" .. tostring(target_col)
        .. " objective_rhs=" .. tostring(lp.objective_rhs)
        .. " objective_nnz=" .. tostring(count_nnz(lp.objective))
        .. " negative_count=" .. tostring(negative_count)
        .. " min_coeff=" .. tostring(min_coeff)
    )
end

function SparseSimplex.solve_current_objective(lp, max_pivots)
    max_pivots = max_pivots or lp.max_pivots

    local ok, bad_row, bad_rhs = validate_primal_feasibility(lp)
    if not ok then
        return {
            status = "infeasible_basis",
            objective = lp.objective_rhs,
            row = bad_row,
            rhs = bad_rhs,
            pivots = 0,
        }
    end

    local start_objective = lp.objective_rhs
    local last_log_objective = lp.objective_rhs

    local degenerate_pivots = 0
    local zero_ratio_pivots = 0

    local approx_window_start_pivot = 0
    local approx_window_start_objective = lp.objective_rhs

    for pivot_count = 1, max_pivots do
        local entering_col, entering_value = choose_entering_col_most_negative(
            lp.objective,
            lp.eps
        )

        if entering_col == nil then
            return {
                status = "optimal",
                objective = lp.objective_rhs,
                pivots = pivot_count - 1,
                degenerate_pivots = degenerate_pivots,
                zero_ratio_pivots = zero_ratio_pivots,
                objective_nnz = count_nnz(lp.objective),
            }
        end

        local leaving_row, min_ratio, ratio_error = choose_leaving_row(lp, entering_col)

        if ratio_error ~= nil then
            ratio_error.objective = lp.objective_rhs
            ratio_error.pivots = pivot_count - 1
            ratio_error.objective_nnz = count_nnz(lp.objective)
            return ratio_error
        end

        if leaving_row == nil then
            return {
                status = "unbounded",
                objective = nil,
                current_objective = lp.objective_rhs,
                pivots = pivot_count - 1,
                entering_col = entering_col,
                entering_value = entering_value,
                objective_nnz = count_nnz(lp.objective),
            }
        end

        local objective_factor = lp.objective[entering_col] or 0
        local predicted_delta = -objective_factor * min_ratio

        if predicted_delta < -lp.monotone_eps then
            return {
                status = "negative_predicted_delta",
                objective = lp.objective_rhs,
                pivots = pivot_count - 1,
                entering_col = entering_col,
                leaving_row = leaving_row,
                objective_factor = objective_factor,
                min_ratio = min_ratio,
                predicted_delta = predicted_delta,
                objective_nnz = count_nnz(lp.objective),
            }
        end

        local should_log = lp.log_interval ~= nil
            and lp.log_interval > 0
            and pivot_count % lp.log_interval == 0

        local entering_col_nnz = nil
        local entering_col_pos = nil
        local entering_col_neg = nil
        local pivot_row_nnz = nil

        if should_log then
            entering_col_nnz, entering_col_pos, entering_col_neg = count_column(lp, entering_col)
            pivot_row_nnz = count_nnz(lp.rows[leaving_row])
        end

        local before = lp.objective_rhs
        local old_basic = lp.basis[leaving_row]

        pivot(lp, leaving_row, entering_col)

        local after = lp.objective_rhs
        local actual_delta = after - before

        if actual_delta < -lp.monotone_eps then
            return {
                status = "objective_decreased",
                before = before,
                after = after,
                delta = actual_delta,
                objective = after,
                pivots = pivot_count,
                entering_col = entering_col,
                leaving_row = leaving_row,
                old_basic = old_basic,
                new_basic = entering_col,
                objective_factor = objective_factor,
                min_ratio = min_ratio,
                predicted_delta = predicted_delta,
                objective_nnz = count_nnz(lp.objective),
            }
        end

        if abs(actual_delta) <= lp.monotone_eps then
            degenerate_pivots = degenerate_pivots + 1
        end

        if min_ratio <= lp.feas_eps then
            zero_ratio_pivots = zero_ratio_pivots + 1
        end

        if should_log then
            lp.logger(
                "SparseSimplex"
                .. " target=" .. tostring(lp.current_target_col)
                .. " pivots=" .. tostring(pivot_count)
                .. " objective=" .. tostring(lp.objective_rhs)
                .. " delta_since_log=" .. tostring(lp.objective_rhs - last_log_objective)
                .. " total_delta=" .. tostring(lp.objective_rhs - start_objective)
                .. " degenerate=" .. tostring(degenerate_pivots)
                .. " zero_ratio=" .. tostring(zero_ratio_pivots)
                .. " objective_nnz=" .. tostring(count_nnz(lp.objective))
                .. " entering=" .. tostring(entering_col)
                .. " entering_value=" .. tostring(entering_value)
                .. " leaving_row=" .. tostring(leaving_row)
                .. " leaving_basic=" .. tostring(old_basic)
                .. " new_basic=" .. tostring(entering_col)
                .. " min_ratio=" .. tostring(min_ratio)
                .. " predicted_delta=" .. tostring(predicted_delta)
                .. " actual_delta=" .. tostring(actual_delta)
                .. " entering_col_nnz=" .. tostring(entering_col_nnz)
                .. " entering_col_pos=" .. tostring(entering_col_pos)
                .. " entering_col_neg=" .. tostring(entering_col_neg)
                .. " pivot_row_nnz=" .. tostring(pivot_row_nnz)
            )

            last_log_objective = lp.objective_rhs
        end

        local approximate_result = should_stop_approximately(
            lp,
            pivot_count,
            approx_window_start_pivot,
            approx_window_start_objective
        )

        if approximate_result ~= nil then
            approximate_result.degenerate_pivots = degenerate_pivots
            approximate_result.zero_ratio_pivots = zero_ratio_pivots
            return approximate_result
        end

        if pivot_count - approx_window_start_pivot >= lp.approx_window then
            approx_window_start_pivot = pivot_count
            approx_window_start_objective = lp.objective_rhs
        end
    end

    return {
        status = "pivot_limit",
        objective = lp.objective_rhs,
        pivots = max_pivots,
        degenerate_pivots = degenerate_pivots,
        zero_ratio_pivots = zero_ratio_pivots,
        objective_nnz = count_nnz(lp.objective),
    }
end

function SparseSimplex.solve_unit_objective(lp, target_col, max_pivots)
    SparseSimplex.set_unit_objective(lp, target_col)
    return SparseSimplex.solve_current_objective(lp, max_pivots)
end

function SparseSimplex.get_basic_solution(lp)
    local solution = {}

    for j = 1, lp.num_original_cols do
        solution[j] = 0
    end

    for i, basic_col in pairs(lp.basis) do
        if basic_col <= lp.num_original_cols then
            solution[basic_col] = lp.rhs[i]
        end
    end

    return solution
end

function SparseSimplex.count_objective_nnz(lp)
    return count_nnz(lp.objective)
end

function SparseSimplex.count_row_nnz(lp, row_index)
    return count_nnz(lp.rows[row_index])
end

function SparseSimplex.count_column_nnz(lp, col)
    local count = count_column(lp, col)
    return count
end

return SparseSimplex