local export = {}

export.technology_node_type = "technology"
export.science_pack_set_node_type = "research-science-pack-set"
export.recipe_node_type = "recipe-surface"
export.item_node_type = "item-surface"
export.fluid_node_type = "fluid-surface"
export.recipe_unlock_node_type = "recipe-tech-unlock"
export.craft_material_node_type = "craft-material-surface"
export.mining_node_type = "mine-entity-surface"
export.craft_material_anywhere_node_type = "craft-material"
export.planet_access_node_type = "planet"
export.space_unlock_node_type = "create-space-platform-tech-unlock"
export.mining_with_fluid_unlock_node_type = "mining-with-fluid-unlock"
export.space_location_discovery_node_type = "space-location-discovery"
export.starting_planet_node_type = "starting-planet"
export.arbitrary_unlock_node_type = "arbitrary-unlock"
export.end_game_node_type = "end-game"
export.spaceship_node_type = "spaceship"
export.rocket_launch_planet_node_type = "rocket-launch-planet"
export.vulcanus_name = "vulcanus"
export.gleba_name = "gleba"
export.fulgora_name = "fulgora"
export.surface_type_planet = "planet"
export.canonical_name = "canonical"
export.electric_energy_distribution_1 = "electric-energy-distribution-1"
export.planet_discovery_vulcanus = "planet-discovery-vulcanus"
export.promethium_science_pack = "promethium-science-pack"

return export