data:extend({
    {
        setting_type = "startup",
        type = "int-setting",
        name = "propertyrandomizer-seed",
        default_value = 0,
        minimum_value = -9007199254740992,
        maximum_value = 9007199254740992,
        order = "a[seed]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-preset",
        allowed_values = {
            "default",
        },
        default_value = "default",
        order = "ab[preset]",
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-bias",
        allowed_values = {
            "worst",
            "worse",
            "default",
            "better",
            "best",
        },
        default_value = "default",
        order = "b-a[bias]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-chaos",
        allowed_values = {
            "light",
            "less",
            "default",
            "more",
            "ultimate",
        },
        default_value = "default",
        order = "b-ba[chaos]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-extra-starting-items",
        default_value = true,
        order = "b-y[extra-starting-items]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-dupes",
        default_value = false,
        order = "b-z[dupes]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-logistic",
        allowed_values = {
            "none",
            "less",
            "default",
            "more",
        },
        default_value = "default",
        order = "c-a[logistic]"
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-production",
        allowed_values = {
            "none",
            "less",
            "default",
            "more",
        },
        default_value = "default",
        order = "c-b[production]"
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-military",
        allowed_values = {
            "none",
            "less",
            "default",
            "more",
        },
        default_value = "default",
        order = "c-c[military]"
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-misc",
        allowed_values = {
            "none",
            "less",
            "default",
            "more",
        },
        default_value = "default",
        order = "c-z[misc]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-preview",
        -- The new unified version for players to try: the unified randomizations still in development, entity randomization, planetary changes other than lightning and freezing, and the tech tree rebuild (config.lua)
        default_value = false,
        order = "d-a[unified-preview]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-technology",
        default_value = false,
        order = "d-c[technology]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-recipe",
        default_value = false,
        order = "d-d[recipe]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-recipe-science-pack",
        default_value = false,
        order = "d-da[science-packs-only]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-recipe-tech-unlock",
        default_value = false,
        order = "d-e[recipe-tech-unlock]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-recipe-tech-unlock-duplicates",
        default_value = false,
        order = "d-ea[recipe-tech-unlock-duplicates]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-item",
        default_value = false,
        order = "d-f[item]",
    },
    {
        setting_type = "startup",
        type = "double-setting",
        name = "propertyrandomizer-item-percent",
        default_value = 100,
        minimum_value = 0,
        maximum_value = 100,
        order = "d-fa[item]",
    },
    {
        setting_type = "startup",
        type = "int-setting",
        name = "propertyrandomizer-item-retries",
        default_value = 10,
        minimum_value = 1,
        order = "d-fb[item]",
    },
    {
        setting_type = "startup",
        type = "int-setting",
        name = "propertyrandomizer-unified-retries",
        default_value = 10,
        minimum_value = 1,
        order = "e-[unified]",
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-dev-unified",
        -- Runs the unified randomizations still in development (the forced handlers in randomizations/graph/unified/execute.lua) in every game
        -- prepare-release.sh turns it off in releases (forced off, so settings saved by development builds can't turn it on), and tests/configs.txt pins it per suite
        -- The unified preview (propertyrandomizer-unified-preview) turns them on too, so it's how releases get them
        default_value = true,
        order = "e-[unified]-a",
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-tech-prereqs",
        default_value = false,
        order = "e-a[tech-prereqs]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-recipe-tech-unlocks",
        default_value = false,
        order = "e-b[recipe-tech-unlocks]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-spoiling",
        -- Visible so the user can try spoiling while it's worked on, and off by default, since the checkout is their playable mod (user, 2026-09-29)
        -- It only takes effect with the other unified randomizations still in development (propertyrandomizer-dev-unified, or the unified preview; see randomizations/graph/unified/execute.lua)
        default_value = false,
        order = "e-c[spoiling]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-tech-science-packs",
        default_value = false,
        order = "e-d[tech-science-packs]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-entity-operation-fluid",
        default_value = false,
        order = "e-e[entity-operation-fluid]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-mining-fluid-required",
        default_value = false,
        order = "e-f[mining-fluid-required]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-entity-autoplace",
        default_value = false,
        order = "e-g[entity-autoplace]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-recipe-ingredients",
        default_value = false,
        order = "e-h[recipe-ingredients]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-item-ingredients",
        default_value = false,
        order = "e-i[item-ingredients]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-item",
        default_value = false,
        order = "e-j[item]",
        hidden = true,
        forced_value = false,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-entity",
        default_value = false,
        order = "e-k[entity]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-unified-entity-biters",
        default_value = false,
        order = "e-ka[entity-biters]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-military-rebalance",
        default_value = true,
        order = "e-kb[military-rebalance]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-unified-technology-delinearization",
        allowed_values = {
            "none",
            "some",
            --"lots",
        },
        default_value = "some",
        order = "f-a[tech-delinearization]",
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-tech-tree-rebuild",
        default_value = false,
        order = "f-b[rebuild]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-oceans",
        default_value = false,
        order = "f-c[planetary-oceans]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-resources",
        default_value = false,
        order = "f-d[planetary-resources]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-lightning",
        default_value = false,
        order = "f-e[planetary-lightning]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-freezing",
        default_value = false,
        order = "f-f[planetary-freezing]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-locks",
        default_value = false,
        order = "f-g[planetary-locks]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-rewards",
        -- Work in progress (notes/wip.txt), off by default: the checkout is the user's playable mod
        default_value = false,
        order = "f-ga[planetary-rewards]",
    },
    {
        -- Work in progress, off by default: outside superposed mode, each planet's science moves into the special machine the permutation brought there (randomizations/planetary/rewards.lua, science_needs and rehome_plan)
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-rewards-rehome",
        default_value = false,
        order = "f-gc[planetary-rewards-rehome]",
        hidden = true,
    },
    {
        -- Development aid: only these reward bundles (technology names, comma-separated) move; empty for all
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-planetary-rewards-only",
        default_value = "",
        allow_blank = true,
        order = "f-gb[planetary-rewards-only]",
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-connections",
        default_value = false,
        order = "f-gb[planetary-connections]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-superposed",
        default_value = false,
        order = "f-h[planetary-superposed]",
    },
    {
        -- Work in progress (randomizations/planetary/fix-pass.lua): the planetary changes repaired by a fix pass with unified's handlers instead of their own repairs
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-planetary-fix-pass",
        default_value = false,
        order = "f-i[planetary-fix-pass]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-icon",
        default_value = false,
        order = "g-a[icon]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-sound",
        default_value = false,
        order = "g-b[sound]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-gui",
        default_value = false,
        order = "g-c[gui]",
    },
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-locale",
        localised_name = "Names",
        localised_description = "Shuffles the names of everything in the game. Why?",
        default_value = false,
        order = "g-d[locale]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-colors",
        allowed_values = {
            "no",
            "little",
            "crazy",
        },
        default_value = "no",
        order = "g-e[colors]",
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-numerical-algorithm",
        allowed_values = {
            "fleishman",
            "exfret-random-walk",
        },
        default_value = "exfret-random-walk",
        order = "h-a[algorithm]",
        -- Deprecated: Fleishman has no bounds, so values can land far from the original (like spoil times of a second), and config.lua always uses the random walk
        hidden = true,
    },
    {
        setting_type = "startup",
        type = "string-setting",
        name = "propertyrandomizer-overrides",
        default_value = "",
        allow_blank = true,
        order = "z-custom-override",
    },
    -- Hidden settings for testing purposes
    {
        setting_type = "startup",
        type = "bool-setting",
        name = "propertyrandomizer-test-unit",
        default_value = false,
        hidden = true,
    },
})