local logic = require("new-lib/logic/init")
logic.build()

local graph_op_test = require("tests/graph-operations")
graph_op_test.init(logic.graph)
graph_op_test.pre_depnode()
graph_op_test.pre_depnodes()

local consistent_sort = require("tests/consistent-sort")
consistent_sort.init(logic.graph)
consistent_sort.validate_all_techs_reachable()
consistent_sort.validate_no_techs_reachable()
consistent_sort.validate_launch_first()
consistent_sort.lava_only_on_vulcanus()
consistent_sort.path_contains_chemical_science()
consistent_sort.path_not_contains_defender()
consistent_sort.path_contains_gleba_biochamber()
consistent_sort.path_not_contains_nauvis_biochamber()