-- Generated by dev/make-dupe-graphics.py; don't edit
-- Original sprite path -> the hue rotations in degrees with a tinted copy at graphics/dupes/tint-<degrees>/<same path> (lib/planet-tints.lua)
return {
    files = {
        ["__base__/graphics/icons/nauvis.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__base__/graphics/icons/starmap-planet-nauvis.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/aquilo.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/fulgora.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/gleba.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/starmap-planet-aquilo.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/starmap-planet-fulgora.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/starmap-planet-gleba.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/starmap-planet-vulcanus.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/icons/vulcanus.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/technology/aquilo.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/technology/fulgora.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/technology/gleba.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
        ["__space-age__/graphics/technology/vulcanus.png"] = {60, 90, 120, 150, 180, 210, 240, 270, 300},
    },
}
