settings = {}
settings.startup = {
    ["propertyrandomizer-seed"] = {value = 3171988},
    ["propertyrandomizer-bias"] = {value = "default"},
    ["propertyrandomizer-chaos"] = {value = "default"},
    ["propertyrandomizer-logistic"] = {value = "default"},
    ["propertyrandomizer-production"] = {value = "default"},
    ["propertyrandomizer-military"] = {value = "default"},
    ["propertyrandomizer-misc"] = {value = "default"},
    ["propertyrandomizer-technology"] = {value = true},
    ["propertyrandomizer-recipe"] = {value = false},
    ["propertyrandomizer-item"] = {value = false},
    ["propertyrandomizer-item-percent"] = {value = 100},
    ["propertyrandomizer-icon"] = {value = false},
    ["propertyrandomizer-sound"] = {value = false},
    ["propertyrandomizer-gui"] = {value = false},
    ["propertyrandomizer-locale"] = {value = false},
    ["propertyrandomizer-overrides"] = {value = ""},
    ["propertyrandomizer-watch-the-world-burn"] = {value = false},
    ["propertyrandomizer-dupes"] = {value = false},
    ["propertyrandomizer-recipe-tech-unlock"] = {value = false},
    ["propertyrandomizer-numerical-algorithm"] = {value = "fleishman"},
}