-- generated by science_flow.py / solve_lp_levels.py
return {
    max_cycle_length = 10,
    protected_edges = {
        ["caged-vrauks"] = {
            ["item: cage"] = {
                min_cycle_length = 2,
                via_product = "item: caged-vrauks",
                cycle_nodes = {
                    "item: caged-vrauks",
                    "item: cage",
                    "item: caged-vrauks",
                },
            },
        },
        ["full-render-vrauks"] = {
            ["item: caged-vrauks"] = {
                min_cycle_length = 2,
                via_product = "item: cage",
                cycle_nodes = {
                    "item: cage",
                    "item: caged-vrauks",
                    "item: cage",
                },
            },
        },
        ["log-wood"] = {
            ["item: log"] = {
                min_cycle_length = 4,
                via_product = "item: wood",
                cycle_nodes = {
                    "item: wood",
                    "item: log",
                    "item: wood-seedling",
                    "item: wood-seeds",
                    "item: wood",
                },
            },
        },
        ["log2"] = {
            ["item: wood-seedling"] = {
                min_cycle_length = 4,
                via_product = "item: log",
                cycle_nodes = {
                    "item: log",
                    "item: wood-seedling",
                    "item: wood-seeds",
                    "item: wood",
                    "item: log",
                },
            },
        },
        ["vrauks-1"] = {
            ["item: cocoon"] = {
                min_cycle_length = 3,
                via_product = "item: barrel",
                cycle_nodes = {
                    "item: barrel",
                    "item: cocoon",
                    "item: water-barrel",
                    "item: barrel",
                },
            },
            ["item: water-barrel"] = {
                min_cycle_length = 2,
                via_product = "item: barrel",
                cycle_nodes = {
                    "item: barrel",
                    "item: water-barrel",
                    "item: barrel",
                },
            },
        },
        ["vrauks-cocoon-1"] = {
            ["item: water-barrel"] = {
                min_cycle_length = 2,
                via_product = "item: barrel",
                cycle_nodes = {
                    "item: barrel",
                    "item: water-barrel",
                    "item: barrel",
                },
            },
        },
        ["water-barrel"] = {
            ["item: barrel"] = {
                min_cycle_length = 2,
                via_product = "item: water-barrel",
                cycle_nodes = {
                    "item: water-barrel",
                    "item: barrel",
                    "item: water-barrel",
                },
            },
        },
        ["wood-seedling"] = {
            ["item: wood-seeds"] = {
                min_cycle_length = 4,
                via_product = "item: wood-seedling",
                cycle_nodes = {
                    "item: wood-seedling",
                    "item: wood-seeds",
                    "item: wood",
                    "item: log",
                    "item: wood-seedling",
                },
            },
        },
        ["wood-seeds"] = {
            ["item: wood"] = {
                min_cycle_length = 4,
                via_product = "item: wood-seeds",
                cycle_nodes = {
                    "item: wood-seeds",
                    "item: wood",
                    "item: log",
                    "item: wood-seedling",
                    "item: wood-seeds",
                },
            },
        },
    },
}
